version: '3.8'

services:
  tomtom-mcp:
    container_name: tomtom-mcp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TOMTOM_API_KEY=${TOMTOM_API_KEY}
      - PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped
    command: node dist/index.js
    # Use stdin/stdout mode for MCP if needed:
    # command: node dist/cli.js
