name: Call Blackduck scan

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: tomtom-internal/github-reusable-workflows/.github/workflows/blackduck-scan.yml@main
    with:
      name: tomtom-mcp
      version: "0.0.1"
    secrets:
      ARTIFACTORY_SAAS_READER_ACCOUNT_NAME: ${{ secrets.ARTIFACTORY_SAAS_READER_ACCOUNT_NAME }}
      ARTIFACTORY_SAAS_READER_ACCOUNT_TOKEN: ${{ secrets.ARTIFACTORY_SAAS_READER_ACCOUNT_TOKEN }}
      BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}